Update shortenertest.yml
Файл отредактирован из-за ошибки:
Run go install golang.org/x/tools/cmd/goimports@latest
go: downloading golang.org/x/tools v0.31.0
go: golang.org/x/tools/cmd/goimports@latest: golang.org/x/tools@v0.31.0 requires go >= 1.23.0 (running go 1.22.12; GOTOOLCHAIN=local)
Error: Process completed with exit code 1.